fixtures:
  repositories:
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    postgresql: 'https://github.com/puppetlabs/puppet-postgresql.git'
    firewall: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
    apt: 'https://github.com/puppetlabs/puppetlabs-apt.git'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat.git'
    file_concat: 'https://github.com/electrical/puppet-lib-file_concat.git'
    systemd: 'https://github.com/camptocamp/puppet-systemd.git'
    cron: 'https://github.com/voxpupuli/puppet-cron.git'
    cron_core: 'https://github.com/puppetlabs/puppetlabs-cron_core.git'
    yumrepo_core: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core.git'
    augeas_core: 'https://github.com/puppetlabs/puppetlabs-augeas_core.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
