fixtures:
  repositories:
    inifile: 'git://github.com/puppetlabs/puppetlabs-inifile.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    postgresql: 'git://github.com/puppetlabs/puppet-postgresql.git'
    firewall: 'git://github.com/puppetlabs/puppetlabs-firewall.git'
    apt: 'git://github.com/puppetlabs/puppetlabs-apt.git'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '2.2.1'
    file_concat: 'git://github.com/electrical/puppet-lib-file_concat.git'
  symlinks:
    puppetdb: '#{source_dir}'
