fixtures:
  repositories:
    inifile: 'git://github.com/puppetlabs/puppetlabs-inifile.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    postgresql:
      repo: 'git://github.com/puppetlabs/puppet-postgresql.git'
      ref: '2.5.0'
    firewall: 'git://github.com/puppetlabs/puppetlabs-firewall.git'
    apt: 'git://github.com/puppetlabs/puppetlabs-apt.git'
    concat: 'git://github.com/ripienaar/puppet-concat.git'
  symlinks:
    puppetdb: '#{source_dir}'
