name 'puppetlabs-puppetdb'
version '1.4.0'
source 'git://github.com/puppetlabs/puppetlabs-puppetdb.git'
author 'Puppet Labs'
description 'PuppetDB resource types'
summary 'PuppetDB resource types'
license 'ASL 2.0'
project_page 'https://github.com/puppetlabs/puppetlabs-puppetdb'

dependency 'cprice404/inifile', '>= 0.10.3'
dependency 'puppetlabs/postgresql', '2.x'
dependency 'puppetlabs/firewall', '>= 0.0.4'
dependency 'puppetlabs/stdlib', '>= 1.0.0'
