name: "ci"

on:
  pull_request:
    branches:
      - "main"
  pull_request_target:
    types: [labeled, reopened]
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Spec:
    if: github.event_name != 'pull_request_target'
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
    secrets: "inherit"

  Acceptance:
    needs: Spec
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@main"
    secrets: "inherit"
    with:
      flags: "--collection-platform-exclude 9:Debian-12"
      runs_on: "ubuntu-24.04"
