name: Labeller

on:
  issues:
    types: [ opened, reopened, labeled, unlabeled ]
  pull_request_target:
    types: [ opened, reopened, labeled, unlabeled ]

jobs:
  label:
    if: contains(fromJson('["puppetlabs","puppet-toy-chest"]'), github.repository_owner)
    uses: "puppetlabs/cat-github-actions/.github/workflows/labeller.yml@release-any-tag"
    secrets: inherit
